# Generated by Django 4.0.4 on 2022-04-18 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Etiqueta')),
                ('backgroundColor', models.CharField(blank=True, max_length=12, null=True, verbose_name='Color fondo')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=300, null=True, verbose_name='Título')),
                ('datetime', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora')),
                ('resume', models.TextField(blank=True, max_length=300, null=True, verbose_name='Resume')),
                ('text', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Texto')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.label')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['id'],
            },
        ),
    ]
