# Generated by Django 4.0.4 on 2022-04-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='post',
            name='readingTime',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tiempo lectura'),
        ),
    ]
