# Generated by Django 4.0.4 on 2022-04-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='label',
        ),
        migrations.AddField(
            model_name='post',
            name='label',
            field=models.ManyToManyField(blank=True, null=True, to='home.label'),
        ),
    ]
