# Generated by Django 4.0.4 on 2022-04-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_post_label_post_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=300, null=True, verbose_name='Título')),
                ('datetime', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora')),
                ('resume', models.TextField(blank=True, max_length=300, null=True, verbose_name='Resume')),
                ('text', models.TextField(blank=True, max_length=12000, null=True, verbose_name='Texto')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Project',
                'ordering': ['-datetime'],
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-datetime'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
