# Generated by Django 4.0.4 on 2022-05-01 17:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_post_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
